# Generated by Django 5.0.1 on 2026-04-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
