# Generated by Django 5.0.1 on 2026-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('student',
                     'Student'),
                    ('supervisor',
                     'Supervisor'),
                    ('coordinator',
                     'Coordinator'),
                    ('dean',
                     'Dean'),
                    ('cod',
                     'COD'),
                    ('director_bps',
                     'Director BPS')],
                default='student',
                max_length=20),
        ),
    ]
