# Generated by Codex on 2026-06-03

from django.db import migrations, models
import django.db.models.deletion


def uniquify_existing_phone_numbers(apps, schema_editor):
    User = apps.get_model('users', 'User')
    seen = set()
    for user in User.objects.order_by('id'):
        if user.phone and user.phone not in seen:
            seen.add(user.phone)
            continue
        user.phone = f'+254{user.id:09d}'[:20]
        while user.phone in seen:
            user.phone = f'+255{user.id:09d}'[:20]
        seen.add(user.phone)
        user.save(update_fields=['phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_updated_at'),
    ]

    operations = [
        migrations.RunPython(
            uniquify_existing_phone_numbers,
            migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='admission_number',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp', to='users.user')),
            ],
            options={
                'db_table': 'email_otps',
                'indexes': [
                    models.Index(fields=['code'], name='email_otps_code_c4f8cb_idx'),
                    models.Index(fields=['expires_at'], name='email_otps_expires_040e75_idx'),
                ],
            },
        ),
    ]
