# Generated by Django 4.2.30 on 2026-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailotp_purpose_used_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['purpose'], name='email_otps_purpose_idx'),
        ),
    ]
