# Generated by Django 5.0.1 on 2026-05-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
