# Generated by Django 5.0.1 on 2026-04-22 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stages', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['student', 'stage_type'], name='stages_student_a7ac32_idx'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['status'], name='stages_status_16795b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('student', 'stage_type')},
        ),
    ]
