# Generated by Django 5.0.1 on 2026-05-01 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
