# Generated by Django 5.0.1 on 2026-04-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stages.stage'),
        ),
    ]
