# Generated by Django 5.0.1 on 2026-04-22 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_initial'),
        ('stages', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minutes',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minutes',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='stages.stage'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['stage', 'doc_type'], name='documents_stage_i_ebb224_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['student'], name='documents_student_c9b435_idx'),
        ),
    ]
