# Generated by Django 5.0.1 on 2026-04-15 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('MINUTES', 'Minutes of Presentation'), ('TRANSCRIPT', 'Academic Transcript'), ('FEE_STATEMENT', 'Fee Statement Balance'), ('PROPOSAL', 'Proposal Document'), ('THESIS', 'Thesis Document'), ('INTENT_TO_SUBMIT', 'Intent to Submit Form'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'pptx'])]),
        ),
    ]
