# Generated by Django 5.0.1 on 2026-05-01 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(
                upload_to='documents/%Y/%m/%d/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            'pdf',
                            'doc',
                            'docx'])]),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='file',
            field=models.FileField(
                upload_to='minutes/%Y/%m/%d/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            'pdf',
                            'doc',
                            'docx'])]),
        ),
    ]
