# Generated by Django 5.0.1 on 2026-05-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_file_alter_minutes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
