# Generated by Django 5.0.1 on 2026-04-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('project_title',
                 models.CharField(
                     blank=True,
                     max_length=255)),
                ('preferred_supervisor',
                 models.CharField(
                     blank=True,
                     choices=[
                         ('Dr. Michael Kipchoge',
                          'Dr. Michael Kipchoge'),
                         ('Prof. Jane Njeri',
                          'Prof. Jane Njeri'),
                         ('Dr. James Omondi',
                          'Dr. James Omondi'),
                         ('Dr. Sarah Mwangi',
                          'Dr. Sarah Mwangi'),
                         ('Prof. David Kiplagat',
                          'Prof. David Kiplagat'),
                         ('Dr. Grace Kariuki',
                          'Dr. Grace Kariuki'),
                         ('Dr. Robert Kimani',
                          'Dr. Robert Kimani'),
                         ('Dr. Alice Ochieng',
                          'Dr. Alice Ochieng'),
                         ('OTHER',
                          'Other (Please specify)')],
                     max_length=255)),
                ('preferred_supervisor_other',
                 models.CharField(
                     blank=True,
                     help_text='If no supervisor is selected or for custom entry',
                     max_length=255)),
                ('current_stage',
                 models.CharField(
                     choices=[
                         ('CONCEPT',
                          'Concept'),
                         ('PROPOSAL',
                          'Proposal'),
                         ('THESIS',
                          'Thesis Submission'),
                         ('COMPLETED',
                          'Completed')],
                     default='CONCEPT',
                     max_length=20)),
                ('profile_complete',
                 models.BooleanField(
                     default=False)),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('updated_at',
                 models.DateTimeField(
                     auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
