# Generated by Django 5.0.1 on 2026-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=255)),
                ('preferred_supervisor', models.CharField(blank=True, choices=[('Professor Okello (Dean)', 'Professor Okello (Dean)'), ('Dr. Prisca Magotu (COD)', 'Dr. Prisca Magotu (COD)'), ('Prof. Miner Titus', 'Prof. Miner Titus'), ('Dr. Joseph Nyakinda', 'Dr. Joseph Nyakinda'), ('Dr. Willy Kangojo (Coordinator)', 'Dr. Willy Kangojo (Coordinator)'), ('Dr. Julius Owino', 'Dr. Julius Owino'), ('Dr. Francis Akwenda Odhiambo', 'Dr. Francis Akwenda Odhiambo'), ('Director BPS', 'Director BPS'), ('OTHER', 'Other (Please specify)')], max_length=255)),
                ('preferred_supervisor_other', models.CharField(blank=True, help_text='If OTHER is selected above', max_length=255)),
                ('current_stage', models.CharField(choices=[('CONCEPT', 'Concept'), ('PROPOSAL', 'Proposal'), ('THESIS', 'Thesis Submission'), ('COMPLETED', 'Completed')], default='CONCEPT', max_length=20)),
                ('profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('specialisation', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supervisors',
            },
        ),
    ]
