# Generated by Django 5.0.1 on 2026-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preferred_supervisor',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Professor Okello (Dean)',
                     'Professor Okello (Dean)'),
                    ('Dr. Prisca Magotu (COD)',
                     'Dr. Prisca Magotu (COD)'),
                    ('Prof. Miner Titus',
                     'Prof. Miner Titus'),
                    ('Dr. Joseph Nyakinda',
                     'Dr. Joseph Nyakinda'),
                    ('Dr. Willy Kangojo (Coordinator)',
                     'Dr. Willy Kangojo (Coordinator)'),
                    ('Dr. Julius Owino',
                     'Dr. Julius Owino'),
                    ('Dr. Francis Akwenda Odhiambo',
                     'Dr. Francis Akwenda Odhiambo'),
                    ('Director BPS',
                     'Director BPS'),
                    ('OTHER',
                     'Other (Please specify)')],
                max_length=255),
        ),
    ]
