# Generated by Django 5.0.1 on 2026-04-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preferred_supervisor',
            field=models.CharField(blank=True, choices=[('Dr. Michael Kipchoge', 'Dr. Michael Kipchoge'), ('Prof. Jane Njeri', 'Prof. Jane Njeri'), ('Dr. James Omondi', 'Dr. James Omondi'), ('Dr. Sarah Mwangi', 'Dr. Sarah Mwangi'), ('Prof. David Kiplagat', 'Prof. David Kiplagat'), ('Dr. Grace Kariuki', 'Dr. Grace Kariuki'), ('Dr. Robert Kimani', 'Dr. Robert Kimani'), ('Dr. Alice Ochieng', 'Dr. Alice Ochieng'), ('OTHER', 'Other (Please specify)')], max_length=255),
        ),
    ]
