# Generated by Django 5.0.1 on 2026-05-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_preferred_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preferred_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_supervisor_other',
            field=models.CharField(blank=True, help_text='If no supervisor is selected from the list or for custom entry', max_length=255),
        ),
    ]
