# Generated by Django 5.0.1 on 2026-04-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_preferred_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preferred_supervisor_other',
            field=models.CharField(blank=True, help_text='If no supervisor is selected or for custom entry', max_length=255),
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
