# Generated by Django 5.0.1 on 2026-05-01 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_change_preferred_supervisor_to_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preferred_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['supervisor', 'coordinator', 'dean', 'cod', 'director_bps'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
